name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare nightly
      uses: actions-rs/toolchains@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: Build
      run: |
        sudo apt-get install -y libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
        cargo build --verbose
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debug-linux
        path: ./target/debug/mkw-distro-tool
  
  build-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare nightly
      uses: actions-rs/toolchains@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: Build
      run: |
        cargo build --verbose
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: debug-windows
        path: ./target/debug/mkw-distro-tool.exe
